#!/bin/bash

if [ "$1" = "home" ];
then
    export DIR=cjami
elif [ "$1" = "work" ];
then
    export DIR=cjamieso
else
    echo "missing argument"
    echo "usage: addkeys home|work"
    exit 1
fi

eval $(ssh-agent -s)
echo "Adding keys"
ssh-add /mnt/c/Users/$DIR/.vagrant.d/insecure_private_key
ssh-add /mnt/c/Users/$DIR/.ssh/id_rsa
ssh-add /mnt/c/Users/$DIR/.ssh/dmz12_private
