#!/bin/bash

function runtests {
    if [ "$TESTTYPE" = "analytics" ]; then
        echo "Starting report/analytics tests"
        export TAGS=@report_analytics
        runbehat
    elif [ "$TESTTYPE" = "sg" ]; then
        echo "Starting blocks/skills_group tests"
        export TAGS=@block_skills_group
        runbehat
    elif [ "$TESTTYPE" = "mail" ]; then
        echo "Starting blocks/course_message tests"
        export TAGS=@block_course_message
        runbehat
    elif [ "$TESTTYPE" = "wip" ]; then
        echo "Starting work-in-progress tests"
        export TAGS=@wip
        runbehat
    elif [ "$TESTTYPE" = "labels" ]; then
        echo "Starting collapsed labels tests"
        export TAGS=@format_collblct
        runbehat
    else
        echo "Test type not found"
    fi
}

function runbehat {
    if [ "$PARALLELRUNS" -gt 1 ]; then
        echo "running behat tests in parallel"
        lsof | grep 4444
        lsof | grep 8000
        PARALLELPERNODE=$(($PARALLELRUNS/$CI_NODE_TOTAL))
        TORUN=$(($CI_NODE_INDEX*$PARALLELPERNODE))
        FROMRUN=$(($TORUN-$PARALLELPERNODE+1))
        php $DIR/admin/tool/behat/cli/run.php --tags=$TAGS --fromrun=$FROMRUN --torun=$TORUN --profile='firefox_{runprocess}' --replace='{runprocess}'
        php $DIR/moodlescripts/get_behat_tests.php /home/travis/moodledata_behat $FROMRUN $TORUN ${PIPESTATUS[0]}
        exitcode=${PIPESTATUS[0]}
        if [ "${exitcode}" -gt 0 ]; then
            echo "re-running tests"
            rerunbehat
        else
            exit $exitcode
        fi
    else
        echo "running single behat test thread"
        $DIR/vendor/bin/behat --config $YMLDIR/behat.yml --tags $TAGS
    fi
}

function rerunbehat {
    echo "re-running failed tests"
    if [ -s "rerun.txt" ]; then
        cat rerun.txt
        while read -r line || [[ -n "$line" ]];
        do
            ln -s $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/behatrun$line
            $DIR/vendor/bin/behat --config $BEHAT_DATAROOT$line/behat/behat.yml --profile="firefox_$line" --tags=$TAGS --rerun
            exitcode=${PIPESTATUS[0]}
            if [ "${exitcode}" -gt 0 ]; then
                exit $exitcode
            fi
        done < "rerun.txt"
    fi
}

# Check for parallel option and default to 1
if [ -z "$PARALLELRUNS" ]; then
    if [ -z "$2" ] ; then
        echo "no option provided for parallel, using 1"
        export PARALLELRUNS=1
    else
        export PARALLELRUNS=$2
    fi
fi

# For non-travis builds, start the jar and xvfb
if [ -z "$TRAVIS_BUILD_DIR" ]; then
    export DIR=/vagrant
    export YMLDIR=/b_moodledata/behat
    start_selenium $PARALLEL
else
    export DIR=$TRAVIS_BUILD_DIR
    export YMLDIR=/home/travis/roots/behatdata/behat
fi

# Use file for tests if it exists, otherwise use $1
if [ -f "paths.txt" ]; then
    while read -r line || [[ -n "$line" ]]; do
        export TESTTYPE=$line
        runtests
    done < "paths.txt"
else
    export TESTTYPE=$1
    runtests
fi
