#!/bin/bash
# behat

# For non-travis builds, start the jar and xvfb
if [ -z "$TRAVIS_BUILD_DIR" ];
then
    export DISPLAY=:10
    (java -jar /home/vagrant/selenium-server-standalone.jar > /dev/null 2>&1)& >/dev/null 2>&1
    (sudo Xvfb :10 -ac -noreset 2>/dev/null & )& > /dev/null 2>&1
fi

# Check for piped input, otherwise use $1
export TESTTYPE=`cat`;
if [ -z $TESTTYPE ];
then
    export $TESTTYPE=$1
fi

if [ "$TESTTYPE" = "analytics" ];
then
	echo "Starting report/analytics tests"
	/vagrant/vendor/bin/behat --config /b_moodledata/behat/behat.yml --tags @report_analytics
elif [ "$TESTTYPE" = "sg" ];
then
	echo "Starting blocks/skills_group tests"
	/vagrant/vendor/bin/behat --config /b_moodledata/behat/behat.yml --tags @block_skills_group
elif [ "$TESTTYPE" = "mail" ];
then
	echo "Starting blocks/course_message tests"
	/vagrant/vendor/bin/behat --config /b_moodledata/behat/behat.yml --tags @block_course_message
elif [ "$TESTTYPE" = "wip" ];
then
	echo "Starting work-in-progress tests"
	/vagrant/vendor/bin/behat --config /b_moodledata/behat/behat.yml --tags @wip
else
	echo "Test type not found"
fi

