#!/bin/bash

if [ "$1" = "clean" ];
then
    ssh vagrant rm -rf /behat_fail/*
    exit 0
else
    UNAME=`ls /mnt/c/Users | grep "^c"`
    if [ -z $UNAME ]; then
        echo "UNAME not correctly located"
        return 1;
    fi
    export DIR=/mnt/c/Users/$UNAME
    scp -rp vagrant:/behat_fail/* $DIR/Desktop
    exit 0
fi
