#!/bin/bash

if [ "$1" = "home" ];
then
    export DIR=cjami
elif [ "$1" = "work" ];
then
    export DIR=cjamieso
elif [ "$1" = "clean" ];
then
    ssh vagrant rm -rf /behat_fail/*
    exit 1
else
    echo "missing argument"
    echo "usage: bfail {home|work}"
    exit 1
fi

scp -rp vagrant:/behat_fail/* /mnt/c/Users/$DIR/Desktop
