#!/bin/bash

if git log --oneline -1 | grep -q "analytics" ; then
	echo 'analytics'
elif git log --oneline -1 | grep -q "mail" ; then
	echo 'mail'
elif git log --oneline -1 | grep -q "skills_group" ; then
	echo 'sg'
elif git log --oneline -1 | grep -q "nurs_navigation" ; then
	echo 'nn'
else
	echo 'Did not find a project trigger to test.';
fi

