#!/bin/bash
# behat

function runchecker {
    if [ "$TESTTYPE" = "analytics" ];
    then
        echo "Running codechecker on report/analytics"
        php $DIR/local/codechecker/run.php /report/analytics
    elif [ "$TESTTYPE" = "sg" ];
    then
        echo "Running codechecker on blocks/skills_group"
        php $DIR/local/codechecker/run.php /blocks/skills_group
    elif [ "$TESTTYPE" = "mail" ];
    then
        echo "Running codechecker on blocks/course_message"
        php $DIR/local/codechecker/run.php /blocks/course_message
    elif [ "$TESTTYPE" = "nn" ];
    then
        echo "Running codechecker on blocks/nurs_navigation"
        php $DIR/local/codechecker/run.php /blocks/nurs_navigation
    else
        echo "Plugin type not found"
    fi
}

# Set home folder
if [ -z "$TRAVIS_BUILD_DIR" ];
then
    export DIR=/vagrant
else
    export DIR=$TRAVIS_BUILD_DIR
fi

# Use file for tests if it exists, otherwise use $1
if [ -f "paths.txt" ];
then
    while read -r line || [[ -n "$line" ]];
    do
        export TESTTYPE=$line
        runchecker
    done < "paths.txt"
else
    export TESTTYPE=$1
    runchecker
fi