#!/bin/bash

export MOODLEVERSION=343
export DIR=~/gitprojects/moodle$MOODLEVERSION/lib/testing

# The wwwroot and dataroot
sed -i \
  -e "s%php composer.phar%composer%" \
  $DIR/lib.php ;

curl -O https://getcomposer.org/composer.phar
echo "Remember to run mdocker composer to move the file over"
