#!/bin/bash

if [ "$1" = "home" ];
then
    export DIR=cjami
elif [ "$1" = "work" ];
then
    export DIR=cjamieso
else
    echo "missing argument"
    echo "usage: lssh home|work servername"
    exit 1
fi

if [ "$2" = "vagrant" ];
then
    ssh -i /mnt/c/Users/$DIR/.vagrant.d/insecure_private_key -p 2222 vagrant@127.0.0.1
elif [ "$2" = "dmz18" ];
then
    ssh -i /mnt/c/Users/$DIR/.ssh/dmz12_private -p 22 cjaimeso@dmz18.nurs.ualberta.ca
elif [ "$2" = "fail" ];
then
    scp -i /mnt/c/Users/$DIR/.vagrant.d/insecure_private_key -P 2222 -rp vagrant@127.0.0.1:/behat_fail/* /mnt/c/Users/$DIR/Desktop
else
    echo "missing argument"
    echo "usage: lssh home|work servername"
    exit 1
fi
