#!/bin/bash

options=$(getopt -o t:i --long tag:,init -- "$@")
eval set -- "$options"

while true ; do
    case "$1" in
        -t|--tag)
            t=1
            tags="$2"
            ;;
        -i|--init)
            init=1
            ;;
        --)
            shift
            break
            ;;
    esac
    shift
done

PROJECTS=~/gitprojects
MOODLEVERSION=343
UNAME=`ls /c/Users | grep "^c"`
if [ -z $UNAME ]; then
    echo "UNAME not correctly located"
    exit 1;
fi
export DIR=/mnt/c/Users/$UNAME
MOODLEDIR=$DIR/gitprojects/moodle$MOODLEVERSION

if [ "$init" == 1 ];
then
    OLDDIR=$(pwd)
    cd $MOODLEDIR
    git clone git://github.com/phpmd/phpmd.git
    cd phpmd
    git submodule update --init
    SYMLINK=/usr/local/bin/composer
    if [ ! -d "$SYMLINK" ]; then
        sudo ln -s $MOODLEDIR/composer.phar /usr/local/bin/composer
    fi
    composer install
    cd $OLDDIR
fi

if [ "$t" == 1 ];
then
    echo "running phpmd on $tags"
    XMLDIR=$DIR/git
    $MOODLEDIR/phpmd/src/bin/phpmd $MOODLEDIR/$tags text $MOODLEDIR/moodlemd.xml
fi
