#!/bin/bash

options=$(getopt -o t:bdoi --long tag:,build,drop,init,output -- "$@")
eval set -- "$options"

while true ; do
    case "$1" in
        -t|--tag)
            t=1
            tags="$2"
            ;;
        -b|--build)
            build=1
            ;;
        -d|--drop)
            drop=1
            ;;
        -i|--init)
            init=1
            ;;
        -o|--output)
            output=1
            ;;
        --)
            shift
            break
            ;;
    esac
    shift
done

export PHP=$(type -p php)
if [ "$drop" = 1 ];
then
    command="php admin/tool/phpunit/cli/util.php --drop"
elif [ "$init" = 1 ];
then
    command="php admin/tool/phpunit/cli/init.php"
elif [ "$build" = 1 ];
then
    command="php admin/tool/phpunit/cli/util.php --buildcomponentconfigs"
else
    # check for tests specified
    if [ "$t" -ne 1 ];
    then
        export PLUGINS=$($PHP -f $DIR/moodlescripts/get_diff.php)
        read -ra arr <<<"$PLUGINS"
    else
       export TESTTYPE=$tags
    fi
    command="vendor/bin/phpunit -c"
fi

# For travis builds, use its home dir, otherwise use /vagrant
if [ -z "$TRAVIS_BUILD_DIR" ];
then
    export DIR=/vagrant
    command="exec webserver ${command} ${TESTTYPE}"
    if [ "$output" = 1 ];
    then
        echo "${command}"
    else
        DOCKERDIR="${MOODLE_DOCKER_WWWROOT}/moodle-docker"
        eval "$DOCKERDIR/bin/moodle-docker-compose ${command}"
    fi
else
    export DIR=$TRAVIS_BUILD_DIR
        for a in "${arr[@]}"; do
            export $TESTTYPE="$a"
            cd $DIR
            eval ${command} ${TESTTYPE}
            cd -
       done
fi
