#!/bin/bash

if [[ "$1" =~ ^[0-9]+$ ]]; then
	echo "pushing to test, wip-LMS-$1"
	echo "numeric detected, pushing to test"
	git push -f origin HEAD:wip-LMS-$1
elif [ "$1" = "dev" ]; then
	echo "pushing code to dev"
	git push eclass-dev HEAD:DEV_31
else
	echo "intended usage: dev | number"
fi

