#!/bin/bash

if [ -z "$1" ]; then
	echo "missing argument"
	echo "usage: rebase branch ontobranch"
	exit 1
fi
if [ -z "$2" ]; then
    if [ -z "$LASTBRANCH" ]; then
        echo "missing argument"
        echo "No last branch found, did you forget to use .?"
        echo "usage: rebase branch ontobranch"
        exit 1
    else
        ONTO="$LASTBRANCH"
    fi
else
    ONTO="$2"
fi

# Check to make sure ontobranch exists locally.
TEMP="$(git branch | egrep "^\*?[[:space:]]+$ONTO")"
if [ -z "$TEMP" ]; then
    echo 'ontobranch does not exist, checking out upstream'
    git checkout -b $ONTO origin/$ONTO
else
    echo 'ontobranch exists, continuing'
fi

# Check if we are currently on the branch to rebase.
BRANCH="$(git name-rev --name-only HEAD)"
if [ "$BRANCH" != "$1" ]; then
	echo "branch is not correct, switching"
	git checkout $1
fi
UPSTREAM="$(git rev-parse HEAD~1)"
export LASTBRANCH="$1"

# This will rebase commits from UPSTREAM->BRANCH (excluding UPSTREAM) on the branch ONTO
git rebase --onto ${ONTO} ${UPSTREAM}

