#!/bin/bash

echo "[Installing docker]"
sudo apt-get update
sudo apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
sudo apt update
apt-cache policy docker-ce
sudo apt install docker-ce
echo "[Starting docker]"
sudo service docker start
echo "[Installing docker-compose]"
sudo apt install docker-compose
echo "[Adding docker group to user and sudo to check]"
sudo usermod -aG docker ${USER}
su - ${USER}
id -nG
exit
