#!/bin/bash

UNAME=`ls /c/Users | grep "^c"`
if [ -z $UNAME ]; then
    echo "UNAME not correctly located"
    return 1;
fi

sudo apt-get update
sudo wget https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.9.2.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
go get -d github.com/jstarks/npiperelay
GOOS=windows go build -o /c/Users/$UNAME/go/bin/npiperelay.exe github.com/jstarks/npiperelay
sudo ln -s /c/Users/$UNAME/go/bin/npiperelay.exe /usr/local/bin/npiperelay.exe
sudo apt install -y socat

# Now, install docker, taken from: https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly
# Environment variables you need to set so you don't have to edit the script below.
export DOCKER_CHANNEL=stable
export DOCKER_COMPOSE_VERSION=1.21.2

# Update the apt package index.
sudo apt-get update

# Install packages to allow apt to use a repository over HTTPS.
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

# Add Docker's official GPG key.
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# Verify the fingerprint.
sudo apt-key fingerprint 0EBFCD88

# Pick the release channel.
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   ${DOCKER_CHANNEL}"

# Update the apt package index.
sudo apt-get update

# Install the latest version of Docker CE.
sudo apt-get install -y docker-ce

# Allow your user to access the Docker CLI without needing root.
sudo usermod -aG docker $USER

# Install Docker Compose.
sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose &&
sudo chmod +x /usr/local/bin/docker-compose

# Finally, setup the docker relay file
touch ~/docker-relay
chmod +x ~/docker-relay
echo -e '#!/bin/sh\nexec socat UNIX-LISTEN:/var/run/docker.sock,fork,group=docker,umask=007 EXEC:"npiperelay.exe -ep -s //./pipe/docker_engine",nofork' > ~/docker-relay
sudo adduser $USER docker

echo "Don't forget to reload wsl so that the group member updates are processed."
echo "Be sure to change /etc/wsl.conf to include the mount point as /c rather than /mnt/c."
