#!/bin/bash

BEHAT_PREFIX='bht_'

PARALLELPERNODE=$(($PARALLELRUNS/$CI_NODE_TOTAL))
TORUN=$(($CI_NODE_INDEX*$PARALLELPERNODE))
FROMRUN=$(($TORUN-$PARALLELPERNODE+1))

# behat setup in config.php (remove call to seutp.php, fill in behat info, replace call to setup.php)
sed -i s/require.*setup.php.*// config.php
echo "\$CFG->behat_wwwroot = 'http://localhost:8000';" >> config.php
echo "\$CFG->behat_dataroot = '$BEHAT_DATAROOT';" >> config.php
echo "\$CFG->behat_prefix = '$BEHAT_PREFIX';" >> config.php
echo "\$CFG->behat_faildump_path = '/home/travis/roots/behatfail';" >> config.php
echo "\$CFG->behat_profiles = [" >> config.php
for ((i=1;i<=$PARALLELRUNS;i+=1)); do echo "'firefox_$i' => ['browser' => 'firefox']," >> config.php; done;
echo "];" >> config.php
echo "\$CFG->behat_parallel_run = array(" >> config.php
for ((i=1;i<=$PARALLELRUNS;i+=1)); do DBSUFFIX=$(($i%$MAXDB+1)) && echo "array('dbname' => '$DBNAME$DBSUFFIX', 'behat_prefix' => '$BEHAT_PREFIX$i')," >> config.php; done;
echo ");" >> config.php
echo "require_once(dirname(__FILE__) . '/lib/setup.php');" >> config.php

# Create directories
mkdir -m777 $BEHAT_DATAROOT
mkdir -m777 -p "$HOME"/roots/behatfail
for ((i=1;i<=$PARALLELRUNS;i+=1)); do mkdir -m777 $BEHAT_DATAROOT$i; done;
php -S localhost:8000 > /dev/null 2>&1 &
php admin/tool/behat/cli/init.php -j=$PARALLELRUNS -m=$PARALLELPERNODE --fromrun=$FROMRUN --torun=$TORUN

# Setup grunt and build the min sources.
if [ "$MOODLEVERSION" = "313" ];
then
    npm install --no-spin
    npm install --no-spin -g grunt-cli
    grunt amd
fi
