#!/bin/bash

# Create a directory for the phpunit dataroot.
mkdir -p "$HOME"/roots/behat

# The phpunit dataroot and prefix..
sed -i \
-e "/require_once/i \\\$CFG->behat_dataroot = '\/home\/travis\/roots\/behat';" \
-e "/require_once/i \\\$CFG->behat_prefix = 'b_';" \
-e "/require_once/i \\\$CFG->behat_wwwroot = 'http://localhost:8000';" \
-e "/require_once/i \\\$CFG->behat_faildump_path = '\/home\/travis\/roots\/behatfail';" \
config.php ;

# Initialise PHPUnit for Moodle.
php admin/tool/behat/cli/init.php
# Setup grunt and build the min sources.
if [ "$MOODLEVERSION" = "313" ];
then
    npm install --no-bin-links
    npm install -g grunt-cli
    grunt amd
fi


# Startup xvfb for display -> moved to "before_install"
# export DISPLAY=:99.0
# /etc/init.d/xvfb start ;
# sleep 3