#!/bin/bash

if [ "$1" = "phpunit" ];
then
	echo "resetting phpunit tests"
	php /vagrant/admin/tool/phpunit/cli/init.php
    php /vagrant/admin/tool/phpunit/cli/util.php --buildcomponentconfigs
elif [ "$1" = "behat" ];
then
	echo "resetting behat tests"
	php /vagrant/admin/tool/behat/cli/init.php
elif [ "$1" = "phpmd" ];
then
    echo "configuring phpmd"
    cd /vagrant/phpmd
    git submodule update --init --recursive
    composer install
else
	echo "incorrect option given, use either phpunit|behat|phpmd"
fi

