#!/bin/bash

USER=`ls /mnt/c/Users | grep "cjami"`
if [ -z $USER ];
then
    echo "user not correctly located"
    return 1;
fi
if [ "$USER" = "cjamieso" ];
then
    export DIR=/mnt/c/Users/cjamieso
elif [ "$USER" = "cjami" ];
then
    export DIR=/mnt/d
else
    echo "user not correctly located"
    return 1;
fi

echo "Code dir is: {$DIR}"
echo "Make sure that node + recess are installed"
echo "Ensure that eclass-unified is set to an updated branch"

sudo rm -rf ~/GitProjects/moodle313/theme/eclass
cp -R ~/GitProjects/eclass-craig/theme/eclass ~/GitProjects/moodle313/theme
cd ~/GitProjects/moodle313/theme/eclass/less
recess --compile --compress eclass.less > ../style/eclass.css
