#!/bin/bash

PROJECTS=~/gitprojects
UNAME=`ls /mnt/c/Users | grep "^c"`
if [ -z $UNAME ]; then
    echo "UNAME not correctly located"
    return 1;
fi
export DIR=/mnt/c/Users/$UNAME

echo "Code dir is: {$DIR}"
echo "Make sure that node + recess are installed"
echo "Ensure that eclass-unified is set to an updated branch"

sudo rm -rf $PROJECTS/moodle343/local/eclass
cp -R $PROJECTS/eclass-craig/local/eclass $PROJECTS/moodle343/local
