#!/bin/bash

PROJECTS=~/gitprojects
USER=`ls /mnt/c/Users | grep "cjami"`
if [ -z $USER ];
then
    echo "user not correctly located"
    return 1;
fi
export DIR=/mnt/c/Users/$USER

echo "Code dir is: {$DIR}"
echo "Make sure that node + recess are installed"
echo "Ensure that eclass-unified is set to an updated branch"

sudo rm -rf $PROJECTS/moodle313/theme/eclass
cp -R $PROJECTS/eclass-craig/theme/eclass $PROJECTS/moodle313/theme
cd $PROJECTS/moodle313/theme/eclass/less
recess --compile --compress eclass.less > ../style/eclass.css
